export const ROLES = {
  SUPERADMIN: 'superadmin',
  ADMIN: 'admin',
  SUPERVISOR: 'supervisor',
  WORKER: 'worker'
};

export const ROUTES_ACCESS = {
  [ROLES.SUPERADMIN]: [
    '/super-admin-dashboard',
    '/Plan-Package',
    '/Plan-request',
    '/user-info',
    '/super-admin-setting',
  ],
  [ROLES.ADMIN]: [
    '/dashboard',
    '/safety-compliance-dashboard',
    '/swms',
    '/editnewSwms/:id',
    '/AddnewSms',
    '/user-management',
    '/settings',
    '/add-project',
    '/ProjectDashboard',
    '/calendar',
    '/diariesTimesheets',
    '/userManagement',
    '/inductions',
    '/AddnewInduction',
    '/audit-equipment',
    '/safety-equipment',
    '/submit-report',
    '/ComplianceDashboard',
    '/AddNewWorker',
    '/template',
    '/equipment',
    '/IncidentReports',
    '/AddIncidentReports',
    '/siteEntry',
    '/siteEntryTable',
    '/siteReview',
    '/addSiteReview',
    '/ITPs',
    '/AddITPs',
    '/checklists',
    '/AddChecklists',
    '/defects',
    '/AddDefectList',
    '/PlantMachinery',
    '/AddToolRegistry',
    '/AddEquipment',
    '/equipment-details/:id',
    '/messenger',
    '/helpSupport',
    '/TaskDashboard',
    '/create-task',
    '/updatetask/:id',
    '/announcements',
    '/AddAnnouncements',
    '/rfis',
    '/AddRFIs',
    '/toolbox',
    '/AddToolboxTalks',
    '/Calendar_createnewtask',
    '/Documents',
    '/upload-new',
    '/architure',
    '/add-document-from',
    '/DrawingRegister',
    '/Doc3DBeamModeling',
    '/AIConstructionAssistant',
    '/ClientPortal',
    '/ReportAnalytics',
    '/AddUserManagement',
    '/edit-audit-equipment/:id',
    '/audit-equipmentview/:id',
    '/auditreport',
    '/edit-toolbox/:id',
    '/edit-user/:id',
    '/users/view/:id',
    '/ComplianceReport',
    '/open-bim',
    '/view-swms/:id',
    '/View-Inductions/:id',
    '/AddSafety',
    '/view-service',
    '/defects/:id',
    '/itps/view/:id',
    '/safety-equipment/:id',
    '/FullSiteMap',
    '/EditAnnouncements/:id'
  ],

  //Super Visor specific routes
  [ROLES.SUPERVISOR]: [
    '/dashboard',
    '/safety-compliance-dashboard',
    '/swms',
    '/inductions',
    '/incident-reports',
   
  ],

  //Worker specific routes
  [ROLES.WORKER]: [
    '/dashboard',
    '/swms',
    '/incident-reports',
    '/toolbox',
   
  ]
};